# -*- coding: utf-8 -*-
"""Fraud Detection_imbalanced_2606

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buNIf7ZMf5oL3QweIBNFQ00hvgzQrvhg

# FRAUD DETECTION CASE STUDIES

# Part 1: Business Understanding

## 1.1 Background Information
This dataset contains credit card transactions made by European cardholders in the year 2023. It comprises over 550,000 records, and the data has been anonymized to protect the cardholders' identities.

## 1.2 Business Objectives
The primary objective of this dataset is to facilitate the development of fraud detection algorithms and models to identify potentially fraudulent transactions.

## 1.3 Data Mining Goals
- Explore data patterns and distributions
- Identify correlations between features
- Handle missing values appropriately
- Apply feature selection techniques
- Build classification model for fraud detection

# Part 2: Data Understanding

## 2.1 Import Libraries and Load Data
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning & Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from imblearn.over_sampling import SMOTE
# Plotting configurations
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

# Load the Kaggle Credit Card Fraud Dataset
# Note: Ensure 'creditcard.csv' is in your directory or Google Drive
try:
    df = pd.read_csv('/content/drive/MyDrive/data/creditcard.csv')
    print(f"✅ Dataset loaded successfully! Shape: {df.shape}")
except FileNotFoundError:
    print("❌ Error: 'creditcard.csv' not found. Please upload it to your workspace.")
    # At the end of your plotting code blocks, make sure this is present:
plt.show()

import sys
!{sys.executable} -m pip install optuna
print('Optuna installed successfully!')

"""## 2.2 Describe Data

Now that the dataset is loaded, we'll perform an initial inspection to understand its structure, data types, and general statistical characteristics. This step is crucial for identifying potential issues and planning subsequent data cleaning and preprocessing.

### 2.2.1 General Characteristics
"""

# Display the number of rows and columns
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

# Display basic information about the DataFrame, including data types and non-null counts
print("\n--- DataFrame Info ---")
df.info()

"""### 2.2.2 Basic Statistics of the Dataset

"""

# Display descriptive statistics for numerical columns
print("\n--- Descriptive Statistics ---")
display(df.describe())

"""### 2.2.3 Feature Renaming

To standardize the feature names and improve readability, we will rename the principal component features (V1-V28) to 'feature_1' through 'feature_28'. This makes it easier to refer to them programmatically.
"""

# Create a dictionary for renaming V-columns to feature_X
rename_dict = {f'V{i}': f'feature_{i}' for i in range(1, 29)}

# Rename the columns in the DataFrame
df = df.rename(columns=rename_dict)

print("Columns renamed successfully!")

# Display the first few rows with new column names
display(df.head())

"""## 2.7 Data Exploration

### 2.7.1 Constant Features
Features that have only one unique value (i.e., constant features) provide no information for machine learning models and can be safely removed. We will identify and list any such features.
"""

# Identify constant features
constant_features = [col for col in df.columns if df[col].nunique() == 1]

if constant_features:
    print(f"Found {len(constant_features)} constant features: {constant_features}")
    # Optionally, drop these features
    # df = df.drop(columns=constant_features)
    # print(f"Removed constant features. New DataFrame shape: {df.shape}")
else:
    print("No constant features found in the DataFrame.")

"""### 2.7.2 Low Variance Features

Features with very low variance might also contribute little to a model's predictive power. While not always removed, it's good to be aware of them. We'll look for features where the standard deviation is very close to zero.
"""

# Identify low variance features (e.g., standard deviation very close to zero)
low_variance_threshold = 0.01
low_variance_features = [col for col in df.columns if df[col].std() < low_variance_threshold and col != 'Class']

if low_variance_features:
    print(f"Found {len(low_variance_features)} low variance features: {low_variance_features}")
    for col in low_variance_features:
        print(f"  - {col}: Std Dev = {df[col].std():.6f}")
else:
    print("No features with variance below the specified threshold found.")

"""### 2.7.3 Target Variable Distribution

The 'Class' column represents whether a transaction is fraudulent (1) or legitimate (0). Analyzing its distribution is essential to understand the class imbalance, a common characteristic in fraud detection datasets. This imbalance often requires special handling during model training.
"""

# Check the distribution of the 'Class' variable
class_distribution = df['Class'].value_counts()

print("Class Distribution:")
display(class_distribution)

print("\nPercentage of each class:")
display(df['Class'].value_counts(normalize=True) * 100)

# Visualize the distribution
plt.figure(figsize=(8, 6))
sns.barplot(x=class_distribution.index, y=class_distribution.values, palette=['skyblue', 'salmon'])
plt.title('Distribution of Transaction Classes (0: Legitimate, 1: Fraudulent)')
plt.xlabel('Class')
plt.ylabel('Number of Transactions')
plt.xticks(ticks=[0, 1], labels=['Legitimate', 'Fraudulent'])
plt.show()

"""## 2.8 Check Data Quality

### 2.8.1 Duplicate Rows Check

Duplicate rows in a dataset can lead to biased models and inaccurate insights. We will identify and remove any duplicate transaction records to ensure data integrity.
"""

duplicate_rows_count = df.duplicated().sum()

print(f"Number of duplicate rows found: {duplicate_rows_count}")

if duplicate_rows_count > 0:
    # Remove duplicate rows
    df_cleaned = df.drop_duplicates()
    print(f"{duplicate_rows_count} duplicate rows removed.")
    print(f"New DataFrame shape after removing duplicates: {df_cleaned.shape}")
    df = df_cleaned # Update df to the cleaned DataFrame
else:
    print("No duplicate rows found.")

"""### 2.8.2 Missing Values Check

Missing values can cause errors or biases in analysis and modeling. We will check for any missing values across all columns and visualize their distribution if any are found.
"""

# Check for missing values
missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]

if not missing_values.empty:
    print("Missing values found per column:")
    print(missing_values)
else:
    print("No missing values found in the DataFrame.")

"""Remove missing values from the data set since they account for such a small percentage of the data

### 2.8.3 Data Distribution Analysis

Understanding the distribution of individual features is essential for identifying potential issues like skewness, outliers, and the overall shape of the data. This analysis will guide us in selecting appropriate preprocessing techniques (e.g., scaling, transformations) if needed.
"""

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
# Exclude 'Class' as its distribution has been analyzed separately
if 'Class' in numeric_cols:
    numeric_cols.remove('Class')

num_features = len(numeric_cols)
num_rows = (num_features + 3) // 4  # Arrange plots in a 4-column grid

plt.figure(figsize=(20, 5 * num_rows))
for i, col in enumerate(numeric_cols):
    plt.subplot(num_rows, 4, i + 1)
    sns.histplot(df[col], kde=True, bins=50, color='skyblue')
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.tight_layout()
plt.show()

"""### 2.8.4 Correlation Analysis

Understanding the relationships between features and with the target variable ('Class') is crucial. A correlation matrix and heatmap will help visualize these relationships.
"""

# Calculate the correlation matrix
correlation_matrix = df.corr()

# Display correlations with the 'Class' variable
class_correlations = correlation_matrix['Class'].sort_values(ascending=False)

print("\nCorrelations with the 'Class' variable:")
display(class_correlations)

# Identify features with strong positive or negative correlations with 'Class'
# Define a threshold for strong correlation
correlation_threshold = 0.5

strong_correlations = class_correlations[(class_correlations > correlation_threshold) | (class_correlations < -correlation_threshold)]

if not strong_correlations.empty:
    print(f"\nFeatures with strong correlation (absolute value > {correlation_threshold}) with 'Class':")
    display(strong_correlations)
else:
    print(f"\nNo features with strong correlation (absolute value > {correlation_threshold}) with 'Class' found.")

# Visualize the correlation matrix as a heatmap
plt.figure(figsize=(20, 18))
sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of All Features')
plt.show()

"""# Part 3: Data Preparation

## 3.1 Data Splitting

We will split the dataset into training and testing sets to evaluate our fraud detection models. A common split is 80% for training and 20% for testing. The 'Class' column is our target variable, and the remaining columns will be used as features.
"""

# Define features (X) and target (y)
X = df.drop(['Class'], axis=1)
y = df['Class']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Original dataset shape: {df.shape}")
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training target shape: {y_train.shape}")
print(f"Testing target shape: {y_test.shape}")

"""## 3.2 Stratified K-Fold Cross-Validation

To ensure robust model evaluation, especially with imbalanced datasets, we will use Stratified K-Fold Cross-Validation. This method preserves the percentage of samples for each class in each fold, which is crucial for fraud detection where the minority class (fraudulent transactions) is rare. We will apply a robust scaling method to the Time and Amount features, perform 3-sigma capping for outlier handling, and then apply SMOTE to handle the imbalance issue inside each fold.
"""

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import RobustScaler
from imblearn.over_sampling import SMOTE
import numpy as np

# Initialize RobustScaler and SMOTE outside the loop
scaler = RobustScaler()
smote = SMOTE(random_state=42)

# Define the number of folds for cross-validation
n_splits = 5 # A common choice for k

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

print(f"Initialized Stratified K-Fold with {n_splits} splits.")

print("Demonstrating preprocessing and data distribution within the first fold:")
for fold, (train_index, val_index) in enumerate(skf.split(X_train, y_train)):
    print(f"\nFold {fold+1}:")

    # Get training and validation data for the current fold
    X_train_fold, X_val_fold = X_train.iloc[train_index].copy(), X_train.iloc[val_index].copy()
    y_train_fold, y_val_fold = y_train.iloc[train_index].copy(), y_train.iloc[val_index].copy()

    # Identify numerical columns for capping (all features)
    numerical_features_for_capping = X_train_fold.columns.tolist()

    # Define helper for 3-sigma capping (temporary for this demo cell)
    def cap_outliers_3sigma_temp(df_in, columns_in):
        df_capped_temp = df_in.copy()
        for col in columns_in:
            mean = df_capped_temp[col].mean()
            std = df_capped_temp[col].std()
            lower_bound = mean - 3 * std
            upper_bound = mean + 3 * std
            df_capped_temp[col] = df_capped_temp[col].clip(lower=lower_bound, upper=upper_bound)
        return df_capped_temp

    # Apply outlier capping to training and validation data within the fold using 3-sigma
    X_train_fold = cap_outliers_3sigma_temp(X_train_fold, numerical_features_for_capping)
    X_val_fold = cap_outliers_3sigma_temp(X_val_fold, numerical_features_for_capping)
    print("  Outliers capped using 3-sigma method for numerical features within the fold.")


    # Apply RobustScaler to 'Time' and 'Amount' columns within the fold
    X_train_fold['Time'] = scaler.fit_transform(X_train_fold[['Time']])
    X_val_fold['Time'] = scaler.transform(X_val_fold[['Time']])

    X_train_fold['Amount'] = scaler.fit_transform(X_train_fold[['Amount']])
    X_val_fold['Amount'] = scaler.transform(X_val_fold[['Amount']])

    print("  RobustScaler applied to 'Time' and 'Amount' for this fold.")

    # Apply SMOTE to the training data of the current fold
    X_train_fold_smote, y_train_fold_smote = smote.fit_resample(X_train_fold, y_train_fold)

    print("  SMOTE applied to training data of this fold.")
    print(f"  Original class distribution in training fold:\n{y_train_fold.value_counts(normalize=True)}")
    print(f"  Class distribution after SMOTE (training fold):\n{y_train_fold_smote.value_counts(normalize=True)}")
    print(f"  Class distribution in VALIDATION fold:\n{y_val_fold.value_counts(normalize=True)}")
    if fold == 0: # Only show details for the first fold for brevity
        # Optional: display head of processed data for the first fold
        # print("  X_train_fold_smote head after scaling and SMOTE:")
        # display(X_train_fold_smote.head())
        break

"""# Part 4: Modelling

## 4.1 Model Training and Evaluation with Cross-Validation

Now we will train several classification models using the preprocessed data within each fold of the Stratified K-Fold Cross-Validation. For each model, we will fit it on the 3-sigma capped, robust-scaled, and SMOTE-resampled training data and evaluate its performance on the validation data for that fold. We will focus on key metrics such as accuracy, precision, recall, F1-score, and ROC AUC, which are particularly important for imbalanced datasets like ours.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier # Removed IsolationForest from import
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, average_precision_score, classification_report # Changed roc_auc_score to average_precision_score
import numpy as np # Ensure np is imported for array operations

# Helper function for 3-sigma outlier capping
def cap_outliers_3sigma(df, columns):
    df_capped = df.copy()
    for col in columns:
        mean = df_capped[col].mean()
        std = df_capped[col].std()
        lower_bound = mean - 3 * std
        upper_bound = mean + 3 * std
        df_capped[col] = df_capped[col].clip(lower=lower_bound, upper=upper_bound)
    return df_capped

# Initialize models (Isolation Forest removed)
models = {
    'Logistic Regression': LogisticRegression(random_state=42, solver='liblinear'),
    'Random Forest': RandomForestClassifier(random_state=42),
    'XGBoost': XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss'),
    'LightGBM': LGBMClassifier(random_state=42, verbose=-1) # verbose=-1 to suppress verbose output
}

# Dictionary to store results for each model and fold
results = {name: {'accuracy': [], 'precision': [], 'recall': [], 'f1_score': [], 'pr_auc': []} for name in models.keys()} # Changed 'roc_auc' to 'pr_auc'

print(f"Starting model training and evaluation across {n_splits} folds...")

for fold, (train_index, val_index) in enumerate(skf.split(X_train, y_train)):
    print(f"\n--- Fold {fold+1}/{n_splits} ---")

    # Get training and validation data for the current fold
    X_train_fold, X_val_fold = X_train.iloc[train_index].copy(), X_train.iloc[val_index].copy()
    y_train_fold, y_val_fold = y_train.iloc[train_index].copy(), y_train.iloc[val_index].copy()

    # Identify numerical columns for capping (all features)
    numerical_features_for_capping = X_train_fold.columns.tolist()

    # Apply outlier capping to training and validation data within the fold using 3-sigma
    X_train_fold = cap_outliers_3sigma(X_train_fold, numerical_features_for_capping)
    X_val_fold = cap_outliers_3sigma(X_val_fold, numerical_features_for_capping)
    print("  Outliers capped using 3-sigma method for numerical features within the fold.")

    # Apply RobustScaler to 'Time' and 'Amount' columns within the fold
    X_train_fold['Time'] = scaler.fit_transform(X_train_fold[['Time']])
    X_val_fold['Time'] = scaler.transform(X_val_fold[['Time']])

    X_train_fold['Amount'] = scaler.fit_transform(X_train_fold[['Amount']])
    X_val_fold['Amount'] = scaler.transform(X_val_fold[['Amount']])

    # Apply SMOTE to the training data of the current fold
    X_train_fold_smote, y_train_fold_smote = smote.fit_resample(X_train_fold, y_train_fold)

    print(f"  Fold {fold+1} Preprocessing Complete. Training samples (SMOTE): {len(y_train_fold_smote)}, Validation samples: {len(y_val_fold)}")

    for name, model in models.items():
        print(f"  Training {name}...")
        # Isolation Forest specific logic is now removed
        model.fit(X_train_fold_smote, y_train_fold_smote)
        y_pred = model.predict(X_val_fold)
        y_proba = model.predict_proba(X_val_fold)[:, 1] # Probability of the positive class (fraud)

        # Calculate metrics
        acc = accuracy_score(y_val_fold, y_pred)
        prec = precision_score(y_val_fold, y_pred, zero_division=0)
        rec = recall_score(y_val_fold, y_pred, zero_division=0)
        f1 = f1_score(y_val_fold, y_pred, zero_division=0)
        pr_auc = average_precision_score(y_val_fold, y_proba) # Calculated PR AUC

        # Store results
        results[name]['accuracy'].append(acc)
        results[name]['precision'].append(prec)
        results[name]['recall'].append(rec)
        results[name]['f1_score'].append(f1)
        results[name]['pr_auc'].append(pr_auc) # Stored PR AUC

        print(f"    {name} - Accuracy: {acc:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}, F1-Score: {f1:.4f}, PR AUC: {pr_auc:.4f}") # Updated print statement
        # print(f"\n    Classification Report for {name} (Fold {fold+1}):\n{classification_report(y_val_fold, y_pred, zero_division=0)}")

# Print average results across all folds
print("\n--- Average Metrics Across All Folds ---")
for name, metrics in results.items():
    print(f"\n{name}:")
    for metric_name, values in metrics.items():
        print(f"  Average {metric_name}: {np.mean(values):.4f} (+/- {np.std(values):.4f})")

"""## 4.2 Hyperparameter Tuning for Top Models

Now that we've identified Random Forest and XGBoost as top performers, we'll fine-tune their hyperparameters to further optimize their performance. We will use `RandomizedSearchCV` for efficiency, combining it with our existing preprocessing steps (outlier capping, robust scaling, and SMOTE) within a pipeline.

First, we need to apply the initial preprocessing (capping and scaling) to the full training and test datasets once. Then, `RandomizedSearchCV` will handle the SMOTE application within its cross-validation loops.
"""

from sklearn.preprocessing import RobustScaler

# Re-initialize scaler and cap_outliers_3sigma for full dataset application
scaler = RobustScaler()

# Ensure `cap_outliers_3sigma` is available from previous cells or redefine if necessary
def cap_outliers_3sigma(df, columns):
    df_capped = df.copy()
    for col in columns:
        mean = df_capped[col].mean()
        std = df_capped[col].std()
        lower_bound = mean - 3 * std
        upper_bound = mean + 3 * std
        df_capped[col] = df_capped[col].clip(lower=lower_bound, upper=upper_bound)
    return df_capped

# Apply 3-sigma outlier capping to X_train
numerical_features_for_capping_full = X_train.columns.tolist() # All features are numerical
X_train_capped = cap_outliers_3sigma(X_train.copy(), numerical_features_for_capping_full)

print("Outliers capped for full training dataset.")

# Apply RobustScaler to 'Time' and 'Amount' in the capped datasets
X_train_processed = X_train_capped.copy()

# Correctly fit and transform both 'Time' and 'Amount' columns together
X_train_processed[['Time', 'Amount']] = scaler.fit_transform(X_train_processed[['Time', 'Amount']])

print("RobustScaler applied to 'Time' and 'Amount' for full training dataset.")

display(X_train_processed.head())

"""### 4.2.1 Hyperparameter Tuning for Random Forest

We will use `RandomizedSearchCV` with a predefined parameter grid for the Random Forest Classifier. The `SMOTE` step will be integrated into the cross-validation process to ensure it's applied correctly to each training fold. The scoring metric will be `average_precision` (PR AUC).
"""

from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.ensemble import RandomForestClassifier
from imblearn.pipeline import Pipeline as ImbPipeline # Use imblearn's pipeline for SMOTE integration
from sklearn.preprocessing import StandardScaler # RobustScaler already applied, StandardScaler for general pipeline usage if needed

# Define the parameter grid for Random Forest
param_grid_rf = {
    'randomforestclassifier__n_estimators': [100, 200, 300],
    'randomforestclassifier__max_features': ['sqrt', 'log2', None],
    'randomforestclassifier__max_depth': [10, 20, 30, None],
    'randomforestclassifier__min_samples_split': [2, 5, 10],
    'randomforestclassifier__min_samples_leaf': [1, 2, 4],
    'randomforestclassifier__bootstrap': [True, False]
}

# Create a pipeline with SMOTE and RandomForestClassifier
# The RobustScaler and capping are applied upfront to X_train_processed
pipeline_rf = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('randomforestclassifier', RandomForestClassifier(random_state=42, n_jobs=-1)) # n_jobs=-1 for parallel processing
])

# Initialize RandomizedSearchCV
random_search_rf = RandomizedSearchCV(
    estimator=pipeline_rf,
    param_distributions=param_grid_rf,
    n_iter=5, # Number of parameter settings that are sampled. Reduce for faster run, increase for better results
    cv=skf, # Use the previously defined StratifiedKFold
    scoring='average_precision',
    random_state=42,
    n_jobs=-1, # Use all available cores
    verbose=2
)

# --- Modification to use a smaller subset of data for faster tuning ---
# Define the fraction of the training data to use for hyperparameter tuning
sampling_fraction = 0.02 # Use 2% of the training data for tuning

# Create a subset of the training data for faster tuning
X_train_subset_rf, _, y_train_subset_rf, _ = train_test_split(
    X_train_processed, y_train, train_size=sampling_fraction, random_state=42, stratify=y_train
)

print(f"Starting RandomizedSearchCV for Random Forest with a {sampling_fraction*100}% subset of the training data...")
print(f"Subset shape: {X_train_subset_rf.shape}")

random_search_rf.fit(X_train_subset_rf, y_train_subset_rf)

print("Random Forest tuning complete!")
print(f"Best parameters for Random Forest: {random_search_rf.best_params_}")
print(f"Best PR AUC score for Random Forest: {random_search_rf.best_score_:.4f}")

"""### 4.2.2 Hyperparameter Tuning for XGBoost

Similarly, we will use `RandomizedSearchCV` to tune the XGBoost Classifier, integrating SMOTE into the cross-validation and using `average_precision` as the scoring metric.
"""

from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split # Ensure train_test_split is imported for sampling

# Define the parameter grid for XGBoost
param_grid_xgb = {
    'xgbclassifier__n_estimators': [100, 200, 300],
    'xgbclassifier__learning_rate': [0.01, 0.05, 0.1, 0.2],
    'xgbclassifier__max_depth': [3, 5, 7, 10],
    'xgbclassifier__subsample': [0.6, 0.8, 1.0],
    'xgbclassifier__colsample_bytree': [0.6, 0.8, 1.0],
    'xgbclassifier__gamma': [0, 0.1, 0.2, 0.5],
    'xgbclassifier__lambda': [0.5, 1, 2],
    'xgbclassifier__alpha': [0, 0.1, 0.2]
}

# Create a pipeline with SMOTE and XGBClassifier
pipeline_xgb = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('xgbclassifier', XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss', n_jobs=-1)) # n_jobs=-1 for parallel processing
])

# Initialize RandomizedSearchCV
random_search_xgb = RandomizedSearchCV(
    estimator=pipeline_xgb,
    param_distributions=param_grid_xgb,
    n_iter=5, # Number of parameter settings that are sampled. Reduce for faster run, increase for better results
    cv=skf, # Use the previously defined StratifiedKFold
    scoring='average_precision',
    random_state=42,
    n_jobs=-1, # Use all available cores
    verbose=2
)

# --- Modification to use a smaller subset of data for faster tuning ---
# Use the same sampling fraction as for Random Forest, or adjust as needed
sampling_fraction = 0.02

# Create a subset of the training data for faster tuning
X_train_subset_xgb, _, y_train_subset_xgb, _ = train_test_split(
    X_train_processed, y_train, train_size=sampling_fraction, random_state=42, stratify=y_train
)

print(f"Starting RandomizedSearchCV for XGBoost with a {sampling_fraction*100}% subset of the training data...")
print(f"Subset shape: {X_train_subset_xgb.shape}")

random_search_xgb.fit(X_train_subset_xgb, y_train_subset_xgb)

print("XGBoost tuning complete!")
print(f"Best parameters for XGBoost: {random_search_xgb.best_params_}")
print(f"Best PR AUC score for XGBoost: {random_search_xgb.best_score_:.4f}")

"""# Part 4: Final Model Training and Evaluation on Test Set

We will now use the best hyperparameters found by `RandomizedSearchCV` to train the Random Forest and XGBoost models on the entire preprocessed training dataset (`X_train_processed`, `y_train`). Subsequently, we will evaluate these final models on the preprocessed test set (`X_test`, `y_test`) to get an unbiased estimate of their performance.
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, average_precision_score, classification_report

# --- Prepare the test data (X_test) with the same preprocessing steps as X_train ---

# Note: The `cap_outliers_3sigma` function and `scaler` (RobustScaler) were already defined and fitted in previous steps.
# We will use the fitted scaler to transform the test data.

# Apply 3-sigma outlier capping to X_test
# Use the numerical features identified during training (all columns except 'Class')
numerical_features_for_capping_test = X_test.columns.tolist()
X_test_capped = cap_outliers_3sigma(X_test.copy(), numerical_features_for_capping_test)

print("Outliers capped for test dataset.")

# Apply RobustScaler to 'Time' and 'Amount' in the capped test dataset
X_test_processed = X_test_capped.copy()

# Correctly transform both 'Time' and 'Amount' columns together
X_test_processed[['Time', 'Amount']] = scaler.transform(X_test_processed[['Time', 'Amount']])

print("RobustScaler applied to 'Time' and 'Amount' for test dataset.")

display(X_test_processed.head())

from sklearn.ensemble import RandomForestClassifier
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

# Helper function to strip prefixes from best_params_
def strip_prefix_params(params, prefix):
    return {key.replace(prefix, ''): value for key, value in params.items()}

print("--- Training Final Random Forest Model ---")

# Get best parameters for Random Forest
best_params_rf = random_search_rf.best_params_
stripped_params_rf = strip_prefix_params(best_params_rf, 'randomforestclassifier__')

# Create final Random Forest pipeline with best parameters
final_rf_pipeline = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('randomforestclassifier', RandomForestClassifier(random_state=42, n_jobs=-1, **stripped_params_rf))
])

# Train the final model on the full preprocessed training data
print("Training Random Forest on full X_train_processed...")
final_rf_pipeline.fit(X_train_processed, y_train)
print("Random Forest training complete.")

# Evaluate on the preprocessed test set
y_pred_rf = final_rf_pipeline.predict(X_test_processed)
y_proba_rf = final_rf_pipeline.predict_proba(X_test_processed)[:, 1]

# Calculate and print metrics
print("\n--- Random Forest Evaluation on Test Set ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_rf, zero_division=0):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_rf, zero_division=0):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_rf, zero_division=0):.4f}")
print(f"PR AUC: {average_precision_score(y_test, y_proba_rf):.4f}")

print("\nClassification Report for Random Forest:")
print(classification_report(y_test, y_pred_rf, zero_division=0))

from xgboost import XGBClassifier
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

# Helper function `strip_prefix_params` is already defined in the previous cell.

print("--- Training Final XGBoost Model ---")

# Get best parameters for XGBoost
best_params_xgb = random_search_xgb.best_params_
stripped_params_xgb = strip_prefix_params(best_params_xgb, 'xgbclassifier__')

# Create final XGBoost pipeline with best parameters
final_xgb_pipeline = ImbPipeline([
    ('smote', SMOTE(random_state=42)),
    ('xgbclassifier', XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss', n_jobs=-1, **stripped_params_xgb))
])

# Train the final model on the full preprocessed training data
print("Training XGBoost on full X_train_processed...")
final_xgb_pipeline.fit(X_train_processed, y_train)
print("XGBoost training complete.")

# Evaluate on the preprocessed test set
y_pred_xgb = final_xgb_pipeline.predict(X_test_processed)
y_proba_xgb = final_xgb_pipeline.predict_proba(X_test_processed)[:, 1]

# Calculate and print metrics
print("\n--- XGBoost Evaluation on Test Set ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred_xgb):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_xgb, zero_division=0):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_xgb, zero_division=0):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred_xgb, zero_division=0):.4f}")
print(f"PR AUC: {average_precision_score(y_test, y_proba_xgb):.4f}")

print("\nClassification Report for XGBoost:")
print(classification_report(y_test, y_pred_xgb, zero_division=0))

"""### Summary of Final Model Performance

The evaluation results on the held-out test set provide an estimate of how the fine-tuned Random Forest and XGBoost models are expected to perform on unseen data. These metrics are crucial for understanding the trade-offs between different models in the context of fraud detection.
"""